### PR TITLE
Build/Actions: Restructure actions

### PR DESCRIPTION
**Pull request by fhaverkamp**
This might need a little review. It might also break some test-cases since the action specific files got moved in the repository. Please have a look.

### CODE REVIEW

**Comment by fhaverkamp** [comment]
Joerg, please have a look at the path's I suggest for the test applications. They are under actions/hls_<name>/sw now and not in software/examples any longer. I wonder if we could setup a path setup to get rid of too much hardcoding there. Long term, I like to have scripts under tests in the action subdirectory.

**Comment by fhaverkamp** [comment]
@boekholt Thanks for adjusting the defaults.

**Comment by fhaverkamp** [comment]
@boekholt I adjusted the path's and corrected some infos. Please have a look.

**Comment by fhaverkamp** [comment]
This patch-set is addressing the following issue: https://github.com/open-power/snap/issues/379.

**Comment by bmesnet** [comment]
I'm ok for this new structure since it makes things easier to find especially for all files in "include" directory.
Shouldn't we take the opportunity to change the name of the action names which are completely confusing.
We are using SNAP_CONFIG to switch from the software action to the hardware action. 
Why wouldn't we clarify all that by calling files as follow;
- application => snap_checksum.c  (no change)
- software action => swaction_checksum.c  (instead of action_checksum.cpp)
- hardware action => hwaction_checksum.cpp (instead of hls_checksum.cpp)

**Comment by joergkayser** [comment]
@fhaverkamp As much as I understand and appreciate, that action hardware and action software is more aligned to each other, we divide the test applications to many places, and software pieces, which may serve several actions, have no home anymore. How do you want to cope with this ?

**Comment by fhaverkamp** [comment]
Bruno, let us do renaming in a separate set of patches. This one should address foremost the location changes of the files and directories, which is complicated enough.

**Comment by joergkayser** [comment]
the configurations with NVMe (including hdl_example) dont work yet, elaboration fails.
Does this new directory structure build the NVMe hardware correctly ?

**Comment by ibm-genwqe** [comment]
Bruno, 
Why not using "hw_checksum" and "sw_checksum" Instead of using long name like "hwaction_checksum"
The code is anyhow in ./actions/....

**Comment by fhaverkamp** [comment]
Hey Sven, a lot of good input from you in those patches. Cool.

**Comment by bmesnet** [comment]
@ibm-genwqe 
Agree that everything is under action directory, but the application is also there!
I was looking to see if we could differentiate the sw and hw action....but this is just a renaming....we can do that later

**Comment by joergkayser** [comment]
FGT+NVME+DDR4+hdl_example  fails during elaboration with
ncelab: *E,CUCPNA: component port ACTION_WRAPPER.M_AXI_NVME_ARADDR not associated with any formal [5.2.1.2].
	   Default binding for instance: top.a0@psl_accel(psl_accel):action_w
branch=SIM_Restructure_Actions f076413 2017-07-19
simulator=irun
see /afs/bb/proj/fpga/framework/jkayser/test_SIM_Restructure_Actions_fgtnvmd/
ACTION_ROOT=/afs/bb/proj/fpga/framework/jkayser/test_SIM_Restructure_Actions_fgtramd/actions/hdl_example

same fail with FGT+NVMe+BRAM+hdl_example
slightly different fail with FGT+hdl_example (no DRAM) : 
ncelab: *E,CUDBPD: Unassociated entity port ACTION_WRAPPER.M_AXI_CARD_MEM0_ARREADY must have a default expression [1.1.1.2].
	   Default binding for instance: top.a0@psl_accel(psl_accel):action_w

**Comment by boekholt** [comment]
Hi @joergkayser, regarding your nvme problem there seems to be a problem with your setup.

Looking into /afs/bb/proj/fpga/framework/jkayser/test_SIM_Restructure_Actions_fgtnvmd/hardware/logs/action_make.log I see it is working in the directory
/afs/bb/proj/fpga/framework/jkayser/test_SIM_Restructure_Actions_fgt**ramd**

**Comment by joergkayser** [comment]
@boekholt Thank You for the hint, with the right actions we now have NVMe running as well. The only fails are with hls_intersect, and this is fixed in another branch and will be merged with this one soon

**Comment by ibm-genwqe** [comment]
The build seems to be broken
Pleas check "SNAP_IMG_KU3_DDR3 origin/SIM_Restructure_Actions #247"
Sven merged in master. This needs to be fixed first

**Comment by boekholt** [comment]
@ibm-genwqe I do not see this problem when trying to reproduce this (cloning the repositories from scratch and simply calling make). Looks like some kind of Jenkins setup problem...

**Comment by boekholt** [comment]
@ibm-genwqe: problem should be fixed with my latest commit.

**Comment by ibm-genwqe** [comment]
------------ Pleas fix "SNAP_ROOT" settings if compiling on ppcle

esa@tul2eth3:~/git-repos/snap (SIM_Restructure_Actions)$ make
make[1]: Entering directory '/home/esa/git-repos/snap/software'
make[2]: Entering directory '/home/esa/git-repos/snap/software/lib'
	[CC]	snap.o
	[CC]	snap.o
	[LD]	__libsnap.o
	[AR]	libsnap.a
	[CC]	libsnap.so.0.1.2-1.1.0-21-g0124
make[2]: Leaving directory '/home/esa/git-repos/snap/software/lib'
make[2]: Entering directory '/home/esa/git-repos/snap/software/tools'
	[CC]	snap_peek.o
	[CC]	force_cpu.o
	[CC]	snap_poke.o
	[CC]	bfs_diff.o
	[CC]	snap_maint.o
	[CC]	snap_nvme_init.o
	[CC]	snap_peek
	[CC]	snap_poke
	[CC]	bfs_diff
	[CC]	snap_maint
	[CC]	snap_nvme_init
make[2]: Leaving directory '/home/esa/git-repos/snap/software/tools'
make[1]: Leaving directory '/home/esa/git-repos/snap/software'
WARNING: Environment variable SNAP_ROOT does not point to a
         directory. Please prepare hardware environment
         (see hardware/README.md) before building hardware.

**Comment by boekholt** [comment]
This is not a bug. It is a feature!

**Comment by ibm-genwqe** [comment]
Perfekt now, works now on ppcle .... Thanks

**Pull request merged**
