### PR TITLE
HW: Build flow fixes

### PR DESCRIPTION
**Pull request by boekholt**

### CODE REVIEW

**Comment by bmesnet** [comment]
Changing the card used doesn't match with the PSL_DCP path!
Can we create 2 variables PSL_DCP_KU3 and PSL_DCP_FGT so that PSL_DCP can be assigned by the configurator to the right one?

**Comment by bmesnet** [comment]
When selecting an action using the configurator (make snap_config), the ACTION_ROOT defined in .snap_env.sh doesn't change !!!

**Comment by kenhill** [comment]
Should #440 be included in this update?

**Comment by kenhill** [comment]
Can we assign a release tag for this merge?

**Pull request merged**
