### PR TITLE
HLS search : wr 64B aligned words in DDR - HLS checksum : saving benchmark code

### PR DESCRIPTION
**Pull request by bmesnet**
…code

Signed-off-by: Bruno Mesnet <bruno.mesnet@fr.ibm.com>

### CODE REVIEW

**Comment by fhaverkamp** [comment]
@jsvogt One of the changes broke the software build test.

**Comment by bmesnet** [comment]
The sponge build needs now the setting SDRAM_USED=FALSE (as well as the BFS)

**Comment by bmesnet** [comment]
I changed the SDRAM_USED=FALSE parameter in jenkins but couldn't change the name _DDR3_ in the build name

**Comment by fhaverkamp** [comment]
Joerg K. and I reviewed the config of the sim test case and changed some things. Let's see if the tests will start working after doing that.

**Pull request closed without merging**
