### PR TITLE
HLS examples : memcpy + search + sponge modifications

### PR DESCRIPTION
**Pull request by bmesnet**
Signed-off-by: Bruno Mesnet <bruno.mesnet@fr.ibm.com>
Memcopy : bigger buffer size
Search : small corrections (correction of Issue #315)
Sponge : push code used for benchmark - adding ifdef to remove unused and non optimized code

### CODE REVIEW

**Comment by joergkayser** [comment]
have you tested hls_search ? I get a timeout with snap_search -m0 -pA -i1.uni -E1 -t440, where i1.uni='A'

**Comment by bmesnet** [comment]
I have some strange behavior on search... need to come back on it later

**Comment by bmesnet** [comment]
@joergkayser , thanks
for sponge, please put SDRAM_USED=FALSE
for snap_memcopy, snap_search, it is interesting to see that it is related to d1c190f . It may help having an explanation to issue #330 i'm looking to understand

**Comment by joergkayser** [comment]
With 0844244 we get better results:
- sponge works fine with SDRAM_USED=FALSE for both irun and xsim.
- intersect works fine for both irun and xsim.

- search works with mode1&2 in irun, I used several small and bigger buffer sizes. xsim works as well, but needs 4..7x longer than irun. This inreased runtime was seen with DRAM before (in this case 10x) and is described in #192

- memcopy fails different, now I get the error msg: "trailing zero verification failed!" when executing snap_memcopy -i 1.in -o 1.out -v -X -t60. Can you please check, that you don't write too many bytes past the designated output buffer ?

**Comment by bmesnet** [comment]
@joergkayser . Great
I have checked for memcopy writing out of bounds. This is due to the patch who writes only full 64 Bytes words, and I have no way to control it.
I have reported that to Xilinx through issue #320. The only way to correct that is to solve the multiple memcpy issues. A new bug tracking number should be opened for that specific issue and added to #320 
Thanks

**Comment by joergkayser** [comment]
@bmesnet OK, then I am fine with your changes, will limit my tests for hls_memcopy for the time being and approve your pull request

**Pull request merged**
