### PR TITLE
Updated application, with warning about DDR buffer used, and some cle…

### PR DESCRIPTION
**Pull request by acastellane**
Hello team,
warnings were added concerning the usage of the SDRAM as buffer for read ans write transfers.
Application has to handle the data protection at SDRAM buffer position.
With regards
Alexandre

### CODE REVIEW

**Comment by boekholt** [comment]
Adding @luyong6 as reviewer since hls_nvme_memcopy is her design.

**Comment by luyong6** [comment]
Alexandre, What does "UNUSED" mean? Does it mean the data only moves to or from the internal temporary DDR4 buffer?   I don't see the difference to original "NVME->CARD_DRAM"

And thanks for the comments on temporary addresses, it is really bad if user don't know them.

**Comment by acastellane** [comment]
你好,
I wanted to have the same as we have in "memcopy". But I'm not sure that the process is the same, as I'm discovering it.
That means to use the FPGA register as source or destination and not have a full transfer from outside ports.

This way Bruno (in regular memcopy) got the timing in 2 steps from source to register, and from register to destination.

If this works also in NVMe, we'll keep this "UNUSED" and document further.

Does this makes sense to you ?

**Comment by acastellane** [comment]
Hi, I didn't know how to have a review on this draft without pulling a request. I will pull request later when changes will be mature .....

**Pull request closed without merging**
